economy:
# choix entre : "economyapi" ou "bedrockeconomy".
  provider: "economyapi"

not-numeric-message: "§cLe prix doit être un nombre."
not-positif-message: "§cLe prix doit être positif."
no-price-message: "§cVeuillez indiquez le prix."
blacklist-item-message: "§cTu ne peux pas vendre cet item dans le market."
sell-item-message: "§aVous venez de mettre en vente x{count} {item} pour ${price} dans le market."
new-item-message:
  enabled: true
  message: "§aLe joueur {player} vient de mettre en vente x{count} {item} pour ${price} dans le market."

# 86400 = 1 jour.
expired-time: 86400

blacklist-items:
  - "diamond"
  - "dirt"